// Initial Enterprise Seed Dataset for DAYFLOW
export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-1001',
    name: 'Sarah Connor',
    email: 'sarah.connor@dayflow.internal',
    role: 'ADMIN',
    department: 'Human Resources',
    designation: 'VP of People Operations',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco HQ',
    joiningDate: '2021-03-15',
    employmentType: 'Full-Time',
    manager: 'CEO Board',
    emergencyContact: {
      name: 'John Connor',
      relation: 'Spouse',
      phone: '+1 (555) 887-9900',
    },
    salary: {
      basic: 11000,
      hra: 3500,
      allowances: 2000,
      deductions: {
        pf: 1320,
        tax: 2850,
        insurance: 350,
      },
      netSalary: 11980,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 22, used: 4, remaining: 18 },
      SICK: { total: 10, used: 2, remaining: 8 },
      CASUAL: { total: 6, used: 1, remaining: 5 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1002',
    name: 'Michael Vance',
    email: 'michael.vance@dayflow.internal',
    role: 'HR',
    department: 'Human Resources',
    designation: 'Senior HR Talent Manager',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 345-6789',
    location: 'San Francisco HQ',
    joiningDate: '2022-06-01',
    employmentType: 'Full-Time',
    manager: 'Sarah Connor',
    emergencyContact: {
      name: 'Laura Vance',
      relation: 'Spouse',
      phone: '+1 (555) 443-2211',
    },
    salary: {
      basic: 7800,
      hra: 2200,
      allowances: 1200,
      deductions: {
        pf: 936,
        tax: 1850,
        insurance: 250,
      },
      netSalary: 8164,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 5, remaining: 13 },
      SICK: { total: 10, used: 1, remaining: 9 },
      CASUAL: { total: 6, used: 2, remaining: 4 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1003',
    name: 'Alex Morgan',
    email: 'alex.morgan@dayflow.internal',
    role: 'EMPLOYEE',
    department: 'Engineering',
    designation: 'Lead Cloud Architect',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 456-7890',
    location: 'Austin Tech Hub',
    joiningDate: '2022-10-10',
    employmentType: 'Full-Time',
    manager: 'CTO Office',
    emergencyContact: {
      name: 'Marcus Morgan',
      relation: 'Brother',
      phone: '+1 (555) 998-1122',
    },
    salary: {
      basic: 9500,
      hra: 2800,
      allowances: 1500,
      deductions: {
        pf: 1140,
        tax: 2300,
        insurance: 300,
      },
      netSalary: 10060,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 4, remaining: 14 },
      SICK: { total: 10, used: 3, remaining: 7 },
      CASUAL: { total: 6, used: 2, remaining: 4 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1004',
    name: 'Priya Sharma',
    email: 'priya.sharma@dayflow.internal',
    role: 'EMPLOYEE',
    department: 'Product & Design',
    designation: 'Lead Product Designer',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 567-8901',
    location: 'San Francisco HQ',
    joiningDate: '2023-02-14',
    employmentType: 'Full-Time',
    manager: 'Director of Product',
    emergencyContact: {
      name: 'Vikram Sharma',
      relation: 'Father',
      phone: '+1 (555) 776-5544',
    },
    salary: {
      basic: 8200,
      hra: 2400,
      allowances: 1300,
      deductions: {
        pf: 984,
        tax: 1950,
        insurance: 280,
      },
      netSalary: 8686,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 6, remaining: 12 },
      SICK: { total: 10, used: 1, remaining: 9 },
      CASUAL: { total: 6, used: 3, remaining: 3 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1005',
    name: 'David Kim',
    email: 'david.kim@dayflow.internal',
    role: 'EMPLOYEE',
    department: 'Sales & Marketing',
    designation: 'Enterprise Account Executive',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 678-9012',
    location: 'New York Branch',
    joiningDate: '2023-05-20',
    employmentType: 'Full-Time',
    manager: 'VP of Sales',
    emergencyContact: {
      name: 'Grace Kim',
      relation: 'Sister',
      phone: '+1 (555) 332-1199',
    },
    salary: {
      basic: 7200,
      hra: 2000,
      allowances: 2500, // commission/allowance
      deductions: {
        pf: 864,
        tax: 2100,
        insurance: 250,
      },
      netSalary: 8486,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 3, remaining: 15 },
      SICK: { total: 10, used: 4, remaining: 6 },
      CASUAL: { total: 6, used: 1, remaining: 5 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1006',
    name: 'Elena Rostova',
    email: 'elena.rostova@dayflow.internal',
    role: 'EMPLOYEE',
    department: 'Engineering',
    designation: 'Senior Backend Engineer',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 789-0123',
    location: 'Remote - Seattle',
    joiningDate: '2023-08-01',
    employmentType: 'Full-Time',
    manager: 'Alex Morgan',
    emergencyContact: {
      name: 'Dmitri Rostov',
      relation: 'Mother',
      phone: '+1 (555) 665-4433',
    },
    salary: {
      basic: 8500,
      hra: 2500,
      allowances: 1400,
      deductions: {
        pf: 1020,
        tax: 2050,
        insurance: 300,
      },
      netSalary: 9030,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 7, remaining: 11 },
      SICK: { total: 10, used: 2, remaining: 8 },
      CASUAL: { total: 6, used: 0, remaining: 6 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
  {
    id: 'EMP-1007',
    name: 'Marcus Chen',
    email: 'marcus.chen@dayflow.internal',
    role: 'EMPLOYEE',
    department: 'Finance & Operations',
    designation: 'Financial Controller',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 890-1234',
    location: 'San Francisco HQ',
    joiningDate: '2022-01-10',
    employmentType: 'Full-Time',
    manager: 'CFO',
    emergencyContact: {
      name: 'Jenny Chen',
      relation: 'Spouse',
      phone: '+1 (555) 221-4455',
    },
    salary: {
      basic: 8900,
      hra: 2600,
      allowances: 1200,
      deductions: {
        pf: 1068,
        tax: 2200,
        insurance: 320,
      },
      netSalary: 9112,
      effectiveDate: '2026-01-01',
      currency: 'USD',
    },
    leaveBalances: {
      PAID: { total: 18, used: 8, remaining: 10 },
      SICK: { total: 10, used: 1, remaining: 9 },
      CASUAL: { total: 6, used: 3, remaining: 3 },
      MATERNITY_PATERNITY: { total: 60, used: 0, remaining: 60 },
    },
  },
];

// Initial Attendance Records
export const INITIAL_ATTENDANCE = [
  {
    id: 'ATT-2026-001',
    employeeId: 'EMP-1001',
    employeeName: 'Sarah Connor',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '08:45 AM',
    checkOut: null,
    status: 'PRESENT',
    totalHours: '04h 42m',
    workMode: 'In-Office',
    ipAddress: '192.168.10.45 (SF HQ)',
  },
  {
    id: 'ATT-2026-002',
    employeeId: 'EMP-1002',
    employeeName: 'Michael Vance',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '09:05 AM',
    checkOut: null,
    status: 'LATE',
    totalHours: '04h 22m',
    workMode: 'In-Office',
    ipAddress: '192.168.10.62 (SF HQ)',
  },
  {
    id: 'ATT-2026-003',
    employeeId: 'EMP-1003',
    employeeName: 'Alex Morgan',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '08:58 AM',
    checkOut: null,
    status: 'PRESENT',
    totalHours: '04h 29m',
    workMode: 'Remote',
    ipAddress: '72.134.88.19 (Austin VPN)',
  },
  {
    id: 'ATT-2026-004',
    employeeId: 'EMP-1004',
    employeeName: 'Priya Sharma',
    department: 'Product & Design',
    date: '2026-08-22',
    checkIn: '09:15 AM',
    checkOut: null,
    status: 'LATE',
    totalHours: '04h 12m',
    workMode: 'In-Office',
    ipAddress: '192.168.10.88 (SF HQ)',
  },
  {
    id: 'ATT-2026-005',
    employeeId: 'EMP-1005',
    employeeName: 'David Kim',
    department: 'Sales & Marketing',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    status: 'ON_LEAVE',
    totalHours: '00h 00m',
    workMode: 'N/A',
    ipAddress: '—',
  },
  {
    id: 'ATT-2026-006',
    employeeId: 'EMP-1006',
    employeeName: 'Elena Rostova',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    status: 'ABSENT',
    totalHours: '00h 00m',
    workMode: 'Remote',
    ipAddress: '—',
  },
  {
    id: 'ATT-2026-007',
    employeeId: 'EMP-1007',
    employeeName: 'Marcus Chen',
    department: 'Finance & Operations',
    date: '2026-08-22',
    checkIn: '08:30 AM',
    checkOut: null,
    status: 'PRESENT',
    totalHours: '04h 57m',
    workMode: 'In-Office',
    ipAddress: '192.168.10.12 (SF HQ)',
  },
];

// Initial Leave Requests Pipeline
export const INITIAL_LEAVES = [
  {
    id: 'LEV-8801',
    employeeId: 'EMP-1003',
    employeeName: 'Alex Morgan',
    department: 'Engineering',
    leaveType: 'PAID',
    startDate: '2026-08-28',
    endDate: '2026-08-29',
    daysCount: 2,
    reason: 'Attending Cloud Architecture Summit in Seattle and taking time off.',
    status: 'PENDING',
    appliedDate: '2026-08-21',
    reviewedBy: null,
    reviewedAt: null,
    comments: null,
    aiClashWarning: {
      hasClash: true,
      clashingWith: ['Elena Rostova (Engineering - Pending Leave)'],
      coverageRatio: '66% Team Capacity Remaining',
      severity: 'REVIEW',
    },
  },
  {
    id: 'LEV-8802',
    employeeId: 'EMP-1005',
    employeeName: 'David Kim',
    department: 'Sales & Marketing',
    leaveType: 'CASUAL',
    startDate: '2026-08-22',
    endDate: '2026-08-22',
    daysCount: 1,
    reason: 'Personal family engagement and bank appointment.',
    status: 'APPROVED',
    appliedDate: '2026-08-19',
    reviewedBy: 'Sarah Connor',
    reviewedAt: '2026-08-20 03:30 PM',
    comments: 'Approved. Enjoy the family event!',
    aiClashWarning: null,
  },
  {
    id: 'LEV-8803',
    employeeId: 'EMP-1004',
    employeeName: 'Priya Sharma',
    department: 'Product & Design',
    leaveType: 'SICK',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    daysCount: 1,
    reason: 'Severe migraine and doctor visit.',
    status: 'APPROVED',
    appliedDate: '2026-08-15',
    reviewedBy: 'Michael Vance',
    reviewedAt: '2026-08-15 10:15 AM',
    comments: 'Rest well Priya.',
    aiClashWarning: null,
  },
  {
    id: 'LEV-8804',
    employeeId: 'EMP-1006',
    employeeName: 'Elena Rostova',
    department: 'Engineering',
    leaveType: 'PAID',
    startDate: '2026-08-28',
    endDate: '2026-09-02',
    daysCount: 4,
    reason: 'Annual family vacation in Lake Tahoe.',
    status: 'PENDING',
    appliedDate: '2026-08-20',
    reviewedBy: null,
    reviewedAt: null,
    comments: null,
    aiClashWarning: {
      hasClash: true,
      clashingWith: ['Alex Morgan (Engineering - Aug 28-29)'],
      coverageRatio: '50% Core Backend Capacity during sprint freeze',
      severity: 'ATTENTION',
    },
  },
];

// Initial AI Workforce Intelligence Insights
export const INITIAL_AI_INSIGHTS = [
  {
    id: 'INS-901',
    title: 'Critical Engineering Staffing Deficit during Q3 Release Freeze',
    severity: 'ATTENTION',
    whatHappened: 'Simultaneous overlapping leave requests submitted by Lead Architect Alex Morgan and Senior Backend Engineer Elena Rostova for August 28–29.',
    evidence: '2 of 3 core backend system maintainers will be offline concurrently during scheduled Production Release v4.2.',
    whyItMatters: 'Zero tier-1 on-call responder coverage for critical microservices infrastructure during the highest traffic window.',
    recommendation: 'Coordinate staggered coverage or request Alex Morgan to designate alternate standby engineer before approving leave.',
    confidence: 96,
    approvalState: 'PENDING_HR_REVIEW',
    timestamp: '2026-08-22 08:30 AM',
    actionLabel: 'Resolve Staffing Clash',
  },
  {
    id: 'INS-902',
    title: 'Recurring Friday Afternoon Early Departure / Attendance Anomaly',
    severity: 'REVIEW',
    whatHappened: 'Sales & Marketing division registered an average checkout time of 3:45 PM on past 3 consecutive Fridays.',
    evidence: '72% drop in logged client outreach activity between 3:00 PM and 6:00 PM on Fridays compared to Tuesday-Thursday average.',
    whyItMatters: 'Missed SLA on enterprise prospect inquiries submitted during European close / US afternoon overlap.',
    recommendation: 'Implement rotating Friday afternoon client coverage shifts across account executives.',
    confidence: 89,
    approvalState: 'PENDING_HR_REVIEW',
    timestamp: '2026-08-21 05:15 PM',
    actionLabel: 'Schedule Sales 1-on-1',
  },
  {
    id: 'INS-903',
    title: 'Product & Design Team Punctuality & Morale Index Optimization',
    severity: 'HEALTHY',
    whatHappened: 'Product & Design team achieved 98.4% on-time sprint delivery with zero burnout flags across past 60 days.',
    evidence: 'Average daily work hours stabilized at 8.2 hrs/day with healthy leave utilization (82% of annual quota on track).',
    whyItMatters: 'Sustainable high velocity indicates optimal team workload balance and strong psychological safety.',
    recommendation: 'Acknowledge team milestone in upcoming all-hands and export operational template for other departments.',
    confidence: 94,
    approvalState: 'APPROVED',
    timestamp: '2026-08-20 11:00 AM',
    actionLabel: 'Share Best Practice',
  },
];

// Initial Security & Audit Event Logs
export const INITIAL_AUDIT_LOGS = [
  {
    id: 'AUD-5501',
    user: 'Sarah Connor',
    role: 'ADMIN',
    action: 'LEAVE_APPROVED',
    entity: 'Leave Request LEV-8802 (David Kim)',
    ipAddress: '192.168.10.45',
    status: 'SUCCESS',
    timestamp: '2026-08-20 15:30:12',
  },
  {
    id: 'AUD-5502',
    user: 'Michael Vance',
    role: 'HR',
    action: 'SALARY_STRUCTURE_VIEWED',
    entity: 'Engineering Compensation Matrix',
    ipAddress: '192.168.10.62',
    status: 'SUCCESS',
    timestamp: '2026-08-21 09:12:44',
  },
  {
    id: 'AUD-5503',
    user: 'Alex Morgan',
    role: 'EMPLOYEE',
    action: 'AI_GUARDRAIL_TRIGGERED',
    entity: 'Unauthorized Access Attempt: Org Salary Roll',
    ipAddress: '72.134.88.19',
    status: 'BLOCKED_BY_GUARDRAIL',
    timestamp: '2026-08-21 16:44:02',
  },
  {
    id: 'AUD-5504',
    user: 'Sarah Connor',
    role: 'ADMIN',
    action: 'EMPLOYEE_ONBOARDED',
    entity: 'Marcus Chen (EMP-1007)',
    ipAddress: '192.168.10.45',
    status: 'SUCCESS',
    timestamp: '2026-08-18 10:20:00',
  },
  {
    id: 'AUD-5505',
    user: 'Alex Morgan',
    role: 'EMPLOYEE',
    action: 'LEAVE_SUBMITTED',
    entity: 'Leave Request LEV-8801',
    ipAddress: '72.134.88.19',
    status: 'SUCCESS',
    timestamp: '2026-08-21 10:44:19',
  },
];

// Initial Real-time Chronological Timeline Events
export const INITIAL_TIMELINE = [
  {
    id: 'EVT-101',
    time: '08:45 AM',
    title: 'Sarah Connor checked in',
    type: 'ATTENDANCE',
    description: 'Biometric punch verified at San Francisco HQ (Terminal 01)',
    badge: 'Check In',
    color: 'emerald',
  },
  {
    id: 'EVT-102',
    time: '08:58 AM',
    title: 'Alex Morgan checked in',
    type: 'ATTENDANCE',
    description: 'Remote VPN session established from Austin, TX',
    badge: 'Remote Check In',
    color: 'blue',
  },
  {
    id: 'EVT-103',
    time: '09:05 AM',
    title: 'Michael Vance checked in (Late Arrival)',
    type: 'ATTENDANCE',
    description: 'Punch registered 5 minutes past grace period at SF HQ',
    badge: 'Late Check In',
    color: 'amber',
  },
  {
    id: 'EVT-104',
    time: '10:44 AM',
    title: 'Leave request submitted by Alex Morgan',
    type: 'LEAVE',
    description: 'Applied for 2-day Paid Leave (August 28–29) for Tech Summit',
    badge: 'Leave Applied',
    color: 'purple',
  },
  {
    id: 'EVT-105',
    time: '11:05 AM',
    title: 'AI Intelligence Flag Generated',
    type: 'AI',
    description: 'AI Workforce Engine detected 2-person coverage clash in Engineering',
    badge: 'AI Alert',
    color: 'rose',
  },
  {
    id: 'EVT-106',
    time: '11:30 AM',
    title: 'Monthly Payroll Batch Simulation Complete',
    type: 'PAYROLL',
    description: 'August salary structure calculated for 7 active employees ($56,538 Net)',
    badge: 'Payroll Ready',
    color: 'emerald',
  },
];

// Initial Notifications
export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-1',
    title: 'Leave Request Pending Approval',
    message: 'Alex Morgan submitted a 2-day Paid Leave request for Aug 28–29.',
    category: 'LEAVE',
    read: false,
    timestamp: '2026-08-22 10:45 AM',
    link: '/leaves',
  },
  {
    id: 'NOTIF-2',
    title: 'AI Anomaly Detected: Engineering Staffing',
    message: 'Potential coverage gap during sprint freeze due to overlapping leave requests.',
    category: 'AI',
    read: false,
    timestamp: '2026-08-22 11:05 AM',
    link: '/ai-insights',
  },
  {
    id: 'NOTIF-3',
    title: 'August Payroll Statement Generated',
    message: 'Your monthly salary statement for August 2026 is now available for download.',
    category: 'PAYROLL',
    read: true,
    timestamp: '2026-08-20 09:00 AM',
    link: '/payroll',
  },
  {
    id: 'NOTIF-4',
    title: 'Attendance Reminder',
    message: 'Please remember to punch out before leaving the workstation.',
    category: 'ATTENDANCE',
    read: true,
    timestamp: '2026-08-21 05:45 PM',
    link: '/attendance',
  },
];
